---
os: linux

services:
- docker

stages:
- name: test
- name: trigger

# One-time installation actions.
# Here we download our trigger-travis script.
install:
- >-
    curl
    --location
    --retry 3
    https://raw.githubusercontent.com/informaticsmatters/trigger-travis/master/trigger-travis.sh
    --output trigger-travis.sh

jobs:
  include:

  - stage: test
    script:
    - ls
