---
os: linux

language: python
python:
- '3.8'

services:
- docker

stages:
- name: test
- name: trigger

# One-time installation actions.
# Here we download our trigger-travis script.
install:
- >-
    curl
    --location
    --retry 3
    https://raw.githubusercontent.com/informaticsmatters/trigger-travis/master/requirements.txt
    --output trigger-travis-requirements.txt
- >-
    curl
    --location
    --retry 3
    https://raw.githubusercontent.com/informaticsmatters/trigger-travis/master/trigger-travis.py
    --output trigger-travis.py
- pip install -r trigger-travis-requirements.txt
- chmod +x trigger-travis.py

jobs:
  include:

  - stage: test
    script:
    - echo "UPSTREAM_VARIABLE=${UPSTREAM_VARIABLE}"
